# Generated by Django 4.0.6 on 2022-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("T", "Teacher"), ("S", "Student")],
                help_text="are you a student or teacher",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
