# Generated by Django 4.0.6 on 2022-08-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_profile_role_alter_profile_role_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="no_telepon",
        ),
        migrations.AddField(
            model_name="teacher",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="nisn",
            field=models.CharField(help_text="nomor induk siswa", max_length=20),
        ),
    ]
