# Generated by Django 4.0.6 on 2022-08-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_profile_img_remove_student_student_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
