# Generated by Django 4.0.6 on 2022-08-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_class_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("teacher", "teacher"), ("student", "student")],
                help_text="are you a student or teacher",
                max_length=10,
            ),
        ),
    ]
