# Generated by Django 4.0.6 on 2022-08-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_profile_role_id_profile_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.student",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="teacher",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.teacher",
            ),
        ),
    ]
