# Generated by Django 4.0.6 on 2022-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_studentclassrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="student_class",
        ),
        migrations.AddField(
            model_name="class",
            name="accepted",
            field=models.ManyToManyField(related_name="accepted", to="core.student"),
        ),
        migrations.AddField(
            model_name="class",
            name="requests",
            field=models.ManyToManyField(related_name="requests", to="core.student"),
        ),
        migrations.DeleteModel(
            name="StudentClassRequest",
        ),
    ]
