# Generated by Django 4.0.6 on 2022-08-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_class_accepted_alter_class_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="excerpt",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
