# Generated by Django 4.0.6 on 2022-08-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_class_accepted_alter_class_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="class"),
        ),
    ]
