# Generated by Django 4.0.6 on 2022-08-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_class_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
