# Generated by Django 4.0.6 on 2022-08-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_alter_teacher_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="accepted",
            field=models.ManyToManyField(
                blank=True, related_name="class_accepted", to="core.student"
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="requests",
            field=models.ManyToManyField(
                blank=True, related_name="class_request", to="core.student"
            ),
        ),
    ]
