# Generated by Django 4.0.6 on 2022-08-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_class_accepted_alter_class_requests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="class_name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
