# Generated by Django 4.0.6 on 2022-08-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_homework_question_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="home_work",
            new_name="homework",
        ),
        migrations.AlterField(
            model_name="homework",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
