# Generated by Django 4.0.6 on 2022-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_rename_home_work_question_homework_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
