# Generated by Django 4.0.6 on 2022-08-26 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_homework_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="expire",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
