# Generated by Django 4.0.6 on 2022-08-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_homework_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
