# Generated by Django 4.0.6 on 2022-09-13 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_answerquestion_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
