# Generated by Django 4.0.6 on 2022-09-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_homework_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
